const IssueType = {
  INITIAL_ISSUE_STATE: 'INITIAL_ISSUE_STATE',
  FETCH_ISSUE_START: 'FETCH_ISSUE_START',
  FETCH_ISSUE_SUCCESS: 'FETCH_ISSUE_SUCCESS',
  FETCH_ISSUE_FAIL: 'FETCH_ISSUE_FAIL',
  CREATE_ISSUE_START: 'CREATE_ISSUE_START',
  CREATE_ISSUE_SUCCESS: 'CREATE_ISSUE_SUCCESS',
  CREATE_ISSUE_FAIL: 'CREATE_ISSUE_FAIL',
};
export default IssueType;
