const ReposType = {
  INITIAL_REPOS_STATE: 'INITIAL_REPOS_STATE',
  FETCH_REPOS_START: 'FETCH_REPOS_START',
  FETCH_REPOS_SUCCESS: 'FETCH_REPOS_SUCCESS',
  FETCH_REPOS_FAIL: 'FETCH_REPOS_FAIL',
};
export default ReposType;
