const UserType = {
  INITIAL_STATE: 'INITIAL_STATE',
  FETCH_USER_START: 'FETCH_USER_START',
  FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
  FETCH_USER_FAIL: 'FETCH_USER_FAIL',
};
export default UserType;
